apiVersion: apps/v1
kind: Deployment
metadata:
  name: appstore-api
  namespace: appstore-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: appstore
  template:
    metadata:
      labels:
        app: appstore
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      # appstore-api-pod container configuration
      - name: appstore-api-pod
        resources:
          limits:
            cpu: "2000m" # Up to 2 full cores
            memory: "4Gi"
          requests:
            cpu: "1000m" # Use 1 full cores
            memory: "2Gi"