apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/appstore/
patchesStrategicMerge:
- ./kind-appstore-patch.yml
images:
- name: appstore-api-image
  newName: appstore-api-arm64
  newTag: 1.0.0
