basePath: /swagger
host: localhost:3000
info:
  contact:
    email: jtseals@renci.org
    name: Joshua Seals
    url: http://www.renci.org/contact
  description: This api is the core functionality of the helxplatform.
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://www.renci.org/gopherhelx-terms-of-service
  title: GopherHelx Appstore Api
  version: "1.0"
paths:
  /dashboard/{userId}:
    get:
      description: return specific user dashboard view
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
      summary: Dashboard
swagger: "2.0"
